### 
GET http://localhost:9000/api/advertisement



### 
POST  http://localhost:9000/api/advertisement
Content-Type: application/json

{
    "userID": "643ce320cad59c48da078211",
    "propertyID": "643ceb5c7222d77b6a46ebc5",
    "price": 1000000,
    "rentingDuration": 4,
    "paymentContition": "unegui",
    "adDuration": 3
}

