### 
GET http://localhost:9000/api/advertisement


### 
GET http://localhost:9000/api/advertisement

###
GET http://localhost:9000/api/advertisement/filter/price


### 
POST  http://localhost:9000/api/advertisement
Content-Type: application/json

{
    "userID": "",
    "propertyID": "",
    "price": 2000000,
    "rentingDuration": 4,
    "paymentContition": "unegui",
    "adDuration": 3
}

### 
GET http://localhost:9000/api/advertisements/644b22e7a8399fb55ac238c9

