### 
GET http://localhost:9000/api/user/643ce320cad59c48da078211644b22e7a8399fb55ac238c9

### 
GET http://localhost:9000/api/users
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImFkZHJlc3MiOnsiZGlzdHJpY3QiOiJUZXN0VXNlcjI3Iiwic3ViZGlzdHJpY3QiOjEsInN0cmVldCI6IlRlc3RVc2VyMjcifSwiX2lkIjoiNjQ0Mjk0OGRiMWZjZDBkNGFkZTIwYmJhIiwidXNlck5hbWUiOiJUZXN0VXNlcjI3IiwiZmlyc3ROYW1lIjoiVGVzdFVzZXIyNyIsImxhc3ROYW1lIjoiVGVzdFVzZXIyNyIsImVtYWlsIjoiVGVzdFVzZXIyN0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCQ0NHZ6a2RNQ3ZQMnpxNnJuNjBDTGd1eDNsRVZIbEM2L1VCRkxKS0dZd1g0WUV1NDh5bHVFRyIsInByb2ZpbGVQaWN0dXJlIjoiaHR0cHM6Ly9waWNzdW0ucGhvdG9zLzUzNi8zNTQiLCJwaG9uZU51bWJlciI6OTk4ODk5ODgsInJhdGluZ0FzUmVudGVyIjoiIiwicmF0aW5nQXNMYW5kbG9yZCI6IiIsImNyZWF0ZWRBdCI6IjIwMjMtMDQtMjFUMTM6NTA6MDUuMTU2WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMjFUMTM6NTA6MDUuMTU2WiIsIl9fdiI6MH0sImlhdCI6MTY4MjMwMjM2MywiZXhwIjoxNjgyMzg4NzYzfQ.gho1lLLsTCk2i-2Ez3oS9p2tNGaVdHGT0lN5X9dUod0


### 
POST  http://localhost:9000/api/users
Content-Type: application/json

{
  "firstName": "TestUser28",
  "lastName": "TestUser28",
  "email": "TestUser28@gmail.com",
  "address": {
    "district": "TestUser28",
    "subdistrict": 1,
    "street": "TestUser28"
  },
  "password": "password",
  "profilePicture": "https://picsum.photos/536/354",
  "phoneNumber": 99889988,
  "ratingAsRenter": "",
  "ratingAsLandlord": ""
}


### 
POST  http://localhost:9000/api/userlogin
Content-Type: application/json

{
  "email": "nado4@gmail.com",
  "password": "123456"
}


### 
PUT  http://localhost:9000/api/user/64530f1bf29eae6760268ed1
Content-Type: application/json

{
  "firstName": "updated2",
  "lastName": "updated2",
  "email": "updated2@gmail.com",
  "address": {
    "district": "updated2",
    "subdistrict": 1,
    "street": "updated2"
  },
  "password": "123456",
  "profilePicture": "https://picsum.photos/536/354",
  "phoneNumber": 99889988,
  "ratingAsRenter": "",
  "ratingAsLandlord": ""
}